### ISSUE TITLE
How to set this addon up?

### ISSUE THREAD

**Issue by DaVince** [Spuds/Elk_reCAPTCHA#1]
I installed the addon as it's a very useful feature, but frankly I can't seem to find the settings to enter the API key or to use it *anywhere*. The readme isn't helping me with this either.

**Comment by Spuds** [comment]
It should have added a Verification Control in the

Admin -> Configuration -> Security and Moderation -> Anti-Spam section of the forum .. if its not showing up its a bug.

**Comment by DaVince** [comment]
Thanks. Nothing seemed to be showing up there for me, but it turned out that the version available on ElkArte's add-on repository was broken. After installing the release available here on Github it shows up properly.
