### ISSUE TITLE
HTTP Error 500 when submitting a form that uses ReCAPTCHA

### ISSUE THREAD

**Issue by DaVince** [Spuds/Elk_reCAPTCHA#2]
So the add-on displays on my forum now, but any form that uses it will immediately fail with an HTTP 500 error when clicking the submit button. For example: http://forums.spheredev.org/index.php?action=contact

Going through my error log, it spits out this error specifically:
```
PHP Fatal error:  Uncaught Error: Class 'ReCaptcha' not f
ound in /var/www/vhosts/spheredev.org/forums/sources/subs/reCaptcha.class.php:116
Stack trace:
#0 /var/www/vhosts/spheredev.org/forums/sources/subs/VerificationControls.class.php(107): Verification_Controls_ReCaptcha->doTest()
#1 /var/www/vhosts/spheredev.org/forums/sources/controllers/Register.controller.php(943): create_control_verification(Array, true)
#2 /var/www/vhosts/spheredev.org/forums/sources/SiteDispatcher.class.php(306): Register_Controller->action_contact()
#3 /var/www/vhosts/spheredev.org/forums/index.php(217): Site_Dispatcher->dispatch()
#4 /var/www/vhosts/spheredev.org/forums/index.php(145): elk_main()
#5 {main}
  thrown in /var/www/vhosts/spheredev.org/forums/sources
/subs/reCaptcha.class.php on line 116, referer: http://forums.spheredev.org/index.php?action=contact
```

Upon further inspection, it indeed doesn't seem like the class ReCaptcha exists there. I'm not really sure how to proceed from here to make it work, though.

**Comment by Spuds** [comment]
I'll take a look and see what may be occurring ... thanks for the report.

**Comment by Spuds** [comment]
Could you please verify that the file ```recaptchalib.php``` is in your /sources/ext directory?  I'm not immediately seeing why its not finding that class

**Comment by DaVince** [comment]
Yeah, although it seemed to be an empty file for some reason. I wonder if something went wrong during installation. I replaced the file with the one available here and the add-on functions properly now, thanks for the help.

**Comment by Spuds** [comment]
Sometimes *nix does / causes strange things when expanding .zip files with directory structures.   I should just use tar balls for addons like that.   Anyway, glad you have it sorted.
